# Generated by Django 5.0.2 on 2024-02-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Diary', 'Diary'), ('Spices', 'Spices')], max_length=100),
        ),
    ]
