# Generated by Django 5.0.2 on 2024-02-27 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_offer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='offer_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='account.products'),
        ),
    ]
