# Generated by Django 5.0.2 on 2024-03-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_products_is_offer_products_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default='added', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(default='Order Placed', max_length=300),
        ),
    ]
